# Generated by Django 4.1.1 on 2022-11-22 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_userperiodinfo_period_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userperiodinfo',
            name='period_start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
