# Generated by Django 4.1.1 on 2022-11-24 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_userperiodinfo_period_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userperiodinfo',
            name='period_length',
            field=models.IntegerField(blank=True, default=28, null=True, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(45)]),
        ),
    ]
