# Generated by Django 4.1.1 on 2022-11-26 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
