# Generated by Django 4.1.1 on 2022-09-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_has_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='has_colors',
            field=models.CharField(blank=True, choices=[('r', 'Red'), ('y', 'Yellow'), ('b', 'Black'), ('w', 'white')], max_length=10, null=True),
        ),
    ]
