# Generated by Django 4.1.1 on 2022-09-29 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_has_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_colors',
        ),
        migrations.CreateModel(
            name='ProductColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=15, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_colors',
            field=models.ManyToManyField(to='products.productcolors'),
        ),
    ]
