# Generated by Django 4.1.1 on 2022-09-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_has_colors_productcolors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolors',
            name='name',
        ),
        migrations.AddField(
            model_name='productcolors',
            name='name',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
