# Generated by Django 4.1.1 on 2022-09-29 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_productcolors_name_productcolors_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolors',
            name='name',
        ),
        migrations.AddField(
            model_name='productcolors',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
