# Generated by Django 4.1.1 on 2022-10-12 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_productcolors_name_productcolors_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_colors',
        ),
    ]
