# Generated by Django 4.1.1 on 2022-10-14 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_product_colors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductColors',
        ),
    ]
